name: Deploy to EC2 through ECR

on:
  push:
    branches:
      - main

env:
  EC2_USERNAME: ec2-user
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: 161680477677
  ECR_REPOSITORY_NAME: saif-ali

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_IMAGE_NAME: $ECR_REGISTRY/${{env.ECR_REPOSITORY_NAME}}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_IMAGE_NAME:$IMAGE_TAG .
        docker push $ECR_IMAGE_NAME:$IMAGE_TAG
        echo "image=$ECR_IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'docker pull $ECR_IMAGE_NAME:$IMAGE_TAG && docker run -d -p 3000:3000 $ECR_IMAGE_NAME:$IMAGE_TAG'
